app:
  name: spring boot application
  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: com.recipemanager.cookingrecipe.controller
    contact-name: Akanksha
    contact-email: akanksha.jain738@gmail.com
    swagger:
      enable: true