DROP TABLE IF EXISTS RECIPE;

CREATE TABLE RECIPE (
  ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  COOKING_INS VARCHAR(255) NOT NULL,
  CREATED_AT DATETIME NOT NULL,
  IS_VEG VARCHAR(255) NOT NULL,
  INGREDIENTS VARCHAR(255) NOT NULL,
  SERVING_SIZE VARCHAR(255) NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  UPDATED_AT DATETIME NOT NULL,
  URL VARCHAR(255) NOT NULL,
);